services:

  postgres:
    image: 'postgres:15.3-alpine'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=xplit_db'
      - 'POSTGRES_PASSWORD=db_password'
      - 'POSTGRES_USER=db_admin'
    ports:
      - '5432'

  axonserver:
    image: 'axoniq/axonserver:latest-dev'
    hostname: axonserver
    restart: unless-stopped
    volumes:
      - axonserver-data:/data
      - axonserver-events:/events
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data
  axonserver-events:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/events
  axonserver-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/config
